/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import static Formularios.Paying.registro;
import javax.swing.JOptionPane;
import superclasess.Person;
import travelagency.Main;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Poke
 */
public class Paying extends javax.swing.JFrame {

    /**
     *
     * Creates new form Paying
     */
    DefaultTableModel model = new DefaultTableModel();

    public Paying() {
        initComponents();

        txt_baseSalary.setEditable(false);
        txt_netSalary.setEditable(false);
        txt_safe.setEditable(false);
        btn_calculate.setEnabled(false);
        btn_delete.setEnabled(true);
        btn_save.setEnabled(false);
        setLocationRelativeTo(this);
        model.addColumn("ID");
        model.addColumn("NOMBRE");
        model.addColumn("SALARIO BRUTO");
        model.addColumn("SALARIO NETO");
        tbt_board.setModel(model);
    }

    //metodo para activar botones de calcular y guardar cuando tenga algo escrito
    public void enableButton() {
        if (txt_hoursWorked.getText().isEmpty() || txt_extraHours.getText().isEmpty()
                || txt_hourlyPay.getText().isEmpty() || txt_extraPayment.getText().isEmpty()
                || txt_id.getText().isEmpty() || txt_saving.getText().isEmpty()
                || txt_schoolSavings.getText().isEmpty()) {

            btn_save.setEnabled(false);
            btn_calculate.setEnabled(false);
        } else {
            btn_save.setEnabled(true);
            btn_calculate.setEnabled(true);
        }

    }
    static Person[] registro = Main.callRegistration();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_hoursWorked = new javax.swing.JTextField();
        txt_extraHours = new javax.swing.JTextField();
        txt_baseSalary = new javax.swing.JTextField();
        txt_hourlyPay = new javax.swing.JTextField();
        txt_saving = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_netSalary = new javax.swing.JTextField();
        btn_calculate = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_schoolSavings = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_safe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbt_board = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_extraPayment = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel2.setText("HORAS TRABAJADAS");

        jLabel3.setText("PAGO POR HORAS");

        jLabel4.setText("SUELDO BRUTO");

        jLabel5.setText("AHORRO DE SALARIO ESCOLAR");

        jLabel6.setText("HORAS EXTRAS");

        jLabel7.setText("NUMERO DE CEDULA");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
        });

        txt_hoursWorked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hoursWorkedActionPerformed(evt);
            }
        });
        txt_hoursWorked.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hoursWorkedKeyReleased(evt);
            }
        });

        txt_extraHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_extraHoursActionPerformed(evt);
            }
        });
        txt_extraHours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_extraHoursKeyReleased(evt);
            }
        });

        txt_baseSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_baseSalaryActionPerformed(evt);
            }
        });
        txt_baseSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_baseSalaryKeyReleased(evt);
            }
        });

        txt_hourlyPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hourlyPayActionPerformed(evt);
            }
        });
        txt_hourlyPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hourlyPayKeyReleased(evt);
            }
        });

        txt_saving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_savingActionPerformed(evt);
            }
        });
        txt_saving.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_savingKeyReleased(evt);
            }
        });

        jLabel8.setText("SUELDO NETO");

        txt_netSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_netSalaryActionPerformed(evt);
            }
        });
        txt_netSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_netSalaryKeyReleased(evt);
            }
        });

        btn_calculate.setText("Calcular");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });

        btn_new.setText("Nuevo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        btn_new.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_newKeyReleased(evt);
            }
        });

        btn_save.setText("Guardar");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        btn_save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_saveKeyReleased(evt);
            }
        });

        btn_exit.setText("Salir");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        btn_exit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_exitKeyReleased(evt);
            }
        });

        jLabel10.setText("AHORRO");

        txt_schoolSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_schoolSavingsActionPerformed(evt);
            }
        });
        txt_schoolSavings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_schoolSavingsKeyReleased(evt);
            }
        });

        jLabel11.setText("SEGURO");

        txt_safe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_safeActionPerformed(evt);
            }
        });
        txt_safe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_safeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_safeKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Descuentos");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Sueldos");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAGO MENSUAL DE EMPLEADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tbt_board.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbt_board.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbt_boardAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tbt_boardAncestorRemoved(evt);
            }
        });
        tbt_board.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbt_boardKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbt_board);

        btn_delete.setText("Borrar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        btn_delete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_deleteKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setText("Llene todos los espacios para habilitar los botones");

        txt_extraPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_extraPaymentKeyReleased(evt);
            }
        });

        jLabel9.setText("PAGO POR HORAS EXTRAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_baseSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_netSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_hoursWorked, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(txt_extraHours, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_saving, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_schoolSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_safe, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_extraPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(txt_hourlyPay, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btn_calculate)
                            .addGap(169, 169, 169)
                            .addComponent(btn_new)
                            .addGap(190, 190, 190)
                            .addComponent(btn_save)
                            .addGap(175, 175, 175)
                            .addComponent(btn_delete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_exit))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_hoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_hourlyPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_extraHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_extraPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txt_baseSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_saving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_schoolSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_netSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_safe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_calculate)
                    .addComponent(btn_new)
                    .addComponent(btn_save)
                    .addComponent(btn_exit)
                    .addComponent(btn_delete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_hoursWorkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoursWorkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hoursWorkedActionPerformed

    private void txt_extraHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_extraHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_extraHoursActionPerformed

    private void txt_baseSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_baseSalaryActionPerformed
        txt_baseSalary.setEnabled(false);
    }//GEN-LAST:event_txt_baseSalaryActionPerformed
    // este metodo hace las operaciones para clacular seguro, salario bruto y salario neto
    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        Main mn = new Main();

        double hourWorked;
        double hourlyRate;
        double minimumWage = 0;
        double extraHours;
        double savings;
        double schoolSavings;
        double netIncome = 0;
        double extraPayment;
        double extra;
        double safe;
        boolean found = false;
        try {
            String id = txt_id.getText();
            hourWorked = Double.parseDouble(txt_hoursWorked.getText());
            extraHours = Double.parseDouble(txt_extraHours.getText());
            hourlyRate = Double.parseDouble(txt_hourlyPay.getText());
            extraPayment = Double.parseDouble(txt_extraPayment.getText());
            savings = Double.parseDouble(txt_saving.getText());
            schoolSavings = Double.parseDouble(txt_schoolSavings.getText());

            for (int i = 0; i < registro.length; i++) {

                if (id.equals(registro[i].getIdentification())) {
                    found = true;
                    minimumWage = hourWorked * hourlyRate;
                    extra = extraHours * extraPayment;
                    minimumWage = minimumWage + extra;
                    safe = minimumWage * 0.1;
                    netIncome = minimumWage - savings - schoolSavings - safe;

                    txt_baseSalary.setText(String.valueOf(minimumWage));
                    txt_netSalary.setText(String.valueOf(netIncome));
                    txt_safe.setText(String.valueOf(safe));

                }
            }
            if (found == false) {
                JOptionPane.showMessageDialog(null, "No se encontro la persona");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Todos los campos no estan llenos");
        }

    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        txt_baseSalary.setText("");
        txt_extraHours.setText("");
        txt_extraPayment.setText("");
        txt_hourlyPay.setText("");
        txt_hoursWorked.setText("");
        txt_id.setText("");
        txt_netSalary.setText("");
        txt_safe.setText("");
        txt_saving.setText("");
        txt_schoolSavings.setText("");
        enableButton();
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);

    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_hourlyPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hourlyPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hourlyPayActionPerformed

    private void txt_safeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_safeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_safeKeyPressed

    private void txt_safeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_safeActionPerformed

    }//GEN-LAST:event_txt_safeActionPerformed

    private void txt_netSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_netSalaryActionPerformed

    }//GEN-LAST:event_txt_netSalaryActionPerformed

    private void tbt_boardAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbt_boardAncestorAdded

    }//GEN-LAST:event_tbt_boardAncestorAdded

    private void tbt_boardAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbt_boardAncestorRemoved

    }//GEN-LAST:event_tbt_boardAncestorRemoved
    // metodo para limpiar todo el jform
    private void clean() {
        txt_baseSalary.setText("");
        txt_extraHours.setText("");
        txt_extraPayment.setText("");
        txt_hourlyPay.setText("");
        txt_hoursWorked.setText("");
        txt_id.setText("");
        txt_netSalary.setText("");
        txt_safe.setText("");
        txt_saving.setText("");
        txt_schoolSavings.setText("");
    }

    //este metodo es para que el boton guardar guarde en la tabla el id, nombre, salario bruto y salario neto
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        Main mn = new Main();

        double minimumWage;
        double netIncome;
        try {
            String id = txt_id.getText();
            minimumWage = Double.parseDouble(txt_baseSalary.getText());
            netIncome = Double.parseDouble(txt_netSalary.getText());
            String bruto = String.valueOf(minimumWage);
            String neto = String.valueOf(netIncome);
            boolean found = false;

            for (int i = 0; i < registro.length; i++) {

                if (id.equals(registro[i].getIdentification())) {
                    found = true;
                    String nam = registro[i].getName();
                    String last = registro[i].getLastName();
                    Object[] data = new Object[4];
                    data[0] = id;
                    data[1] = nam + " " + last;
                    data[2] = bruto;
                    data[3] = neto;
                    model.addRow(data);
                    clean();
                }
            }
            if (found == false) {
                JOptionPane.showMessageDialog(null, "No se encontro la persona");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "llene los espacios, calcule el salario base y bruto");
        }
    }//GEN-LAST:event_btn_saveActionPerformed
    //metodo para borrar una fila de la tabla de planilla de pago
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int delete = tbt_board.getSelectedRowCount();
        try {

            if (delete >= 0) {
                model.removeRow(delete);
            } else {
                JOptionPane.showMessageDialog(null, "No hay datos por Eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay datos por Eliminar");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        enableButton();
    }//GEN-LAST:event_txt_idKeyReleased

    private void txt_hoursWorkedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hoursWorkedKeyReleased
        char validate = evt.getKeyChar();
        if (Character.isLetter(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showInternalMessageDialog(rootPane, "Ingrese solo numeros");
        }
        enableButton();
    }//GEN-LAST:event_txt_hoursWorkedKeyReleased

    private void txt_extraHoursKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_extraHoursKeyReleased
        char validate = evt.getKeyChar();
        if (Character.isLetter(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showInternalMessageDialog(rootPane, "Ingrese solo numeros");
        }
        enableButton();
    }//GEN-LAST:event_txt_extraHoursKeyReleased

    private void txt_hourlyPayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hourlyPayKeyReleased
        char validate = evt.getKeyChar();
        if (Character.isLetter(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showInternalMessageDialog(rootPane, "Ingrese solo numeros");
        }
        enableButton();
    }//GEN-LAST:event_txt_hourlyPayKeyReleased

    private void txt_extraPaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_extraPaymentKeyReleased
        char validate = evt.getKeyChar();
        if (Character.isLetter(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showInternalMessageDialog(rootPane, "Ingrese solo numeros");
        }
        enableButton();
    }//GEN-LAST:event_txt_extraPaymentKeyReleased

    private void txt_savingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_savingActionPerformed

    }//GEN-LAST:event_txt_savingActionPerformed

    private void txt_schoolSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_schoolSavingsActionPerformed

    }//GEN-LAST:event_txt_schoolSavingsActionPerformed

    private void txt_baseSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_baseSalaryKeyReleased
        enableButton();
    }//GEN-LAST:event_txt_baseSalaryKeyReleased

    private void txt_netSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_netSalaryKeyReleased
        enableButton();
    }//GEN-LAST:event_txt_netSalaryKeyReleased

    private void txt_safeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_safeKeyReleased
        enableButton();
    }//GEN-LAST:event_txt_safeKeyReleased

    private void btn_newKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_newKeyReleased
        enableButton();
    }//GEN-LAST:event_btn_newKeyReleased

    private void btn_deleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_deleteKeyReleased
        enableButton();
    }//GEN-LAST:event_btn_deleteKeyReleased

    private void btn_exitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_exitKeyReleased
        enableButton();
    }//GEN-LAST:event_btn_exitKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        enableButton();
    }//GEN-LAST:event_formKeyReleased

    private void btn_saveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_saveKeyReleased
        enableButton();
    }//GEN-LAST:event_btn_saveKeyReleased

    private void tbt_boardKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbt_boardKeyReleased
        enableButton();
    }//GEN-LAST:event_tbt_boardKeyReleased

    private void txt_savingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_savingKeyReleased
        char validate = evt.getKeyChar();
        if (Character.isLetter(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showInternalMessageDialog(rootPane, "Ingrese solo numeros");
        }
        enableButton();
    }//GEN-LAST:event_txt_savingKeyReleased

    private void txt_schoolSavingsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_schoolSavingsKeyReleased
            char validate = evt.getKeyChar();
        if (Character.isLetter(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showInternalMessageDialog(rootPane, "Ingrese solo numeros");
        }
        enableButton();
    }//GEN-LAST:event_txt_schoolSavingsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paying.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paying.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paying.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paying.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paying().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbt_board;
    private javax.swing.JTextField txt_baseSalary;
    private javax.swing.JTextField txt_extraHours;
    private javax.swing.JTextField txt_extraPayment;
    private javax.swing.JTextField txt_hourlyPay;
    private javax.swing.JTextField txt_hoursWorked;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_netSalary;
    private javax.swing.JTextField txt_safe;
    private javax.swing.JTextField txt_saving;
    private javax.swing.JTextField txt_schoolSavings;
    // End of variables declaration//GEN-END:variables
}
